from __future__ import annotations

from copy import deepcopy
import math
from typing import Any, Mapping


_RUNTIME_MANIFEST: dict[str, Any] = {
    "core_profile": "v8_preference_conditioned_multiobjective",
    "production_action": "pair_plus_wait_v1",
    "worker_action": "pair_plus_wait_v1",
    "policy_head": 8,
    "candidate_ranker": "simplex_softplus_objective_experts_v8",
    "worker_feasibility": "instant_physical_pair_mask_v1",
    "wait_mask": "progress_certified_wait_v2",
    "observation_schema": 6,
    "time_context": "order_chain_action_context_v1",
    "reward": "single_stage_progress_quality_failure_v2",
    "terminal_failure_penalty": 2.0,
    "training_protocol": "single_stage_lexicographic_failure_v2",
}

_REMOVED_NETWORK_FIELDS = frozenset(
    {
        "encoder_type",
        "production_action_edge_features",
        "worker_action_edge_features",
        "production_candidate_relative_features",
        "worker_candidate_relative_features",
        "production_action_semantics",
        "worker_action_semantics",
        "production_relative_feature_names",
        "worker_relative_feature_names",
        "relative_weight_parameterization",
        "candidate_context_mode",
        "worker_relative_weight_sharing",
        "production_commit_set_scorer",
        "future_value_features",
        "preference_" + "conditioning",
        "preference_action_score",
        "production_gate",
        "centered_preference_adapter",
    }
)


def runtime_manifest(config: Mapping[str, Any] | None = None) -> dict[str, Any]:
    """Return implementation identity and the configured task-failure penalty."""

    manifest = deepcopy(_RUNTIME_MANIFEST)
    if config is not None:
        manifest["terminal_failure_penalty"] = float(
            config.get("reward", {}).get(
                "terminal_failure_penalty", manifest["terminal_failure_penalty"]
            )
        )
    return manifest


def validate_latest_only_config(config: Mapping[str, Any]) -> None:
    """Reject removed implementation selectors before a run can start."""

    if "runtime_manifest" in config:
        raise ValueError("runtime_manifest is generated by the repository")
    if str(config.get("experiment_suite_version", "")) != (
        "single_stage_progress_quality_failure_v2"
    ):
        raise ValueError(
            "experiment_suite_version must match the failure-v2 reward contract"
        )
    network = config.get("network", {})
    if not isinstance(network, Mapping):
        raise TypeError("network config must be a mapping")
    removed = sorted(_REMOVED_NETWORK_FIELDS.intersection(network))
    if removed:
        raise ValueError(
            "latest-only configuration cannot select network implementations: "
            + ", ".join(removed)
        )
    if int(network.get("policy_head_version", 8)) != 8:
        raise ValueError("latest-only runtime accepts only policy_head_version=8")
    scalarizer = config.get("objective_scalarizer", {})
    if scalarizer.get("type") != "normalized_augmented_tchebycheff_v1":
        raise ValueError("objective_scalarizer.type must be normalized_augmented_tchebycheff_v1")
    if scalarizer.get("scale_source") != "frozen_manifest":
        raise ValueError("objective_scalarizer.scale_source must be frozen_manifest")
    reward = config.get("reward", {})
    if not isinstance(reward, Mapping):
        raise TypeError("reward config must be a mapping")
    if "quality_weights" in reward:
        raise ValueError(
            "V8 objective preference must be configured only through "
            "preference.quality; reward.quality_weights is not accepted"
        )
    if str(reward.get("mode", "")) != "single_stage_progress_quality_failure_v2":
        raise ValueError(
            "latest-only runtime requires "
            "single_stage_progress_quality_failure_v2"
        )
    try:
        failure_penalty = float(reward.get("terminal_failure_penalty", -1.0))
    except (TypeError, ValueError, OverflowError) as error:
        raise ValueError(
            "reward.terminal_failure_penalty must be finite and non-negative"
        ) from error
    if not math.isfinite(failure_penalty) or failure_penalty < 0.0:
        raise ValueError(
            "reward.terminal_failure_penalty must be finite and non-negative"
        )
    shaping = reward.get("feasibility_shaping", {})
    if not isinstance(shaping, Mapping):
        raise TypeError("reward.feasibility_shaping must be a mapping")
    if bool(shaping.get("enabled", False)):
        raise ValueError("single-stage failure-v2 requires feasibility shaping disabled")
    ppo = config.get("ppo", {})
    if not isinstance(ppo, Mapping):
        raise TypeError("ppo config must be a mapping")
    if float(ppo.get("gamma", 1.0)) != 1.0:
        raise ValueError("single-stage telescoping reward requires ppo.gamma = 1.0")
    training = config.get("training", {})
    if not isinstance(training, Mapping):
        raise TypeError("training config must be a mapping")
    if "two_stage" in training:
        raise ValueError("single-stage runtime rejects training.two_stage")
    environment = config.get("environment", {})
    if not isinstance(environment, Mapping):
        raise TypeError("environment config must be a mapping")
    removed_environment = sorted(
        {"worker_resource_control", "production_defer"}.intersection(
            environment
        )
    )
    if removed_environment:
        raise ValueError(
            "latest-only configuration rejects removed environment controls: "
            + ", ".join(removed_environment)
        )


def attach_runtime_manifest(config: dict[str, Any]) -> dict[str, Any]:
    validate_latest_only_config(config)
    config["runtime_manifest"] = runtime_manifest(config)
    return config
