from __future__ import annotations

from copy import deepcopy
from typing import Any, Mapping


_RUNTIME_MANIFEST: dict[str, Any] = {
    "core_profile": "e1_latest",
    "production_action": "pair_plus_wait_v1",
    "worker_action": "pair_plus_wait_v1",
    "policy_head": 7,
    "candidate_ranker": "bounded_ranker_scale_v7",
    "worker_feasibility": "instant_physical_pair_mask_v1",
    "wait_mask": "progress_completion_lower_bound_v1",
    "observation_schema": 4,
    "training_protocol": "v7_e1_single_objective_protocol_v5",
}

_REMOVED_NETWORK_FIELDS = frozenset(
    {
        "policy_head_version",
        "encoder_type",
        "production_action_edge_features",
        "worker_action_edge_features",
        "production_candidate_relative_features",
        "worker_candidate_relative_features",
        "production_action_semantics",
        "worker_action_semantics",
        "production_relative_feature_names",
        "worker_relative_feature_names",
        "relative_weight_parameterization",
        "candidate_context_mode",
        "worker_relative_weight_sharing",
        "production_commit_set_scorer",
        "future_value_features",
        "preference_" + "conditioning",
        "preference_action_score",
        "production_gate",
        "centered_preference_adapter",
    }
)


def runtime_manifest() -> dict[str, Any]:
    """Return the immutable implementation identity persisted with each run."""

    return deepcopy(_RUNTIME_MANIFEST)


def validate_latest_only_config(config: Mapping[str, Any]) -> None:
    """Reject removed implementation selectors before a run can start."""

    if "runtime_manifest" in config:
        raise ValueError("runtime_manifest is generated by the repository")
    network = config.get("network", {})
    if not isinstance(network, Mapping):
        raise TypeError("network config must be a mapping")
    removed = sorted(_REMOVED_NETWORK_FIELDS.intersection(network))
    if removed:
        raise ValueError(
            "latest-only configuration cannot select network implementations: "
            + ", ".join(removed)
        )
    environment = config.get("environment", {})
    if not isinstance(environment, Mapping):
        raise TypeError("environment config must be a mapping")
    removed_environment = sorted(
        {"worker_resource_control", "production_defer"}.intersection(
            environment
        )
    )
    if removed_environment:
        raise ValueError(
            "latest-only configuration rejects removed environment controls: "
            + ", ".join(removed_environment)
        )


def attach_runtime_manifest(config: dict[str, Any]) -> dict[str, Any]:
    validate_latest_only_config(config)
    config["runtime_manifest"] = runtime_manifest()
    return config
